Pin Werkzeug version to 2.0.2 Resolves: ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' https://werkzeug.palletsprojects.com/en/2.1.x/changes/#version-2-1-0 safe_str_cmp removed in version 2.1.0 (Released 2022-03-28)